cleanup error messages

diff --git a/bin/far2l b/bin/far2l
--- a/bin/far2l
+++ b/bin/far2l
@@ -4,7 +4,7 @@ set -euf
 far2l="$HOME/.local/bin/far2l"
 
 if [ ! -x "$far2l" ] ; then
-    echo "ERROR: '$far2l' not found"
+    >&2 echo "E [$0] '$far2l' not found"
     exit 1
 fi
 
diff --git a/bin/heli-x b/bin/heli-x
--- a/bin/heli-x
+++ b/bin/heli-x
@@ -4,7 +4,7 @@ set -euf
 INPUT="input/js0"
 
 if [ ! -r "/dev/$INPUT" ] ; then
-    >&2 echo "ERROR"
+    >&2 echo "E [$0] input '$INPUT' not found"
     exit 1
 fi
 
@@ -20,7 +20,7 @@ case "$NAME" in
             "/dev/$INPUT"
         ;;
     *)
-        >&2 echo "ERROR"
+        >&2 echo "E [$0] device '$NAME' not known"
         exit 1
         ;;
 esac
