[bin] heli-x - check controller name

diff --git a/bin/heli-x b/bin/heli-x
--- a/bin/heli-x
+++ b/bin/heli-x
@@ -1,24 +1,27 @@
 #!/bin/sh
 set -euf
 
-set -x
-
 INPUT="input/js0"
 
 if [ ! -r "/dev/$INPUT" ] ; then
+    >&2 echo "ERROR"
     exit 1
 fi
 
 NAME=$(cat "/sys/class/$INPUT/device/name")
 
 case "$NAME" in
-    *) # Devo-10 Deviation
+    *Deviation*) # Devo-10 Deviation
         jscal --set-mappings \
             8,0,1,2,3,4,5,6,7,4,288,289,290,291 \
             "/dev/$INPUT"
         jscal --set-correction \
             8,1,200,0,0,5368545,5368545,1,200,0,0,-5368545,-5368545,1,200,0,0,5368545,5368545,1,200,0,0,-5368545,-5368545,1,0,40,40,-2147483648,-2147483648,1,200,0,0,5368545,5368545,1,0,0,0,-2147483648,-2147483648,1,0,0,0,-2147483648,-2147483648 \
             "/dev/$INPUT"
+        ;;
+    *)
+        >&2 echo "ERROR"
+        exit 1
         ;;
 esac
 
